### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by WilfredAlmeida** [DSC-TCET/gdsc-tcet-website#11]
Add CONTRIBUTING.md file with detailed instructions on how an absolute layman can contribute to the repo.

**Comment by whythoSanskar** [comment]
@WilfredAlmeida, I'll work on this issue

**Comment by prathikshetty2002** [comment]
@whythoSanskar also append the hacktoberfest contribution guidelines to it. I will send it to you cool🚀

**Comment by whythoSanskar** [comment]
@prathikshetty2002 sure I'll add hacktoberfest guidelines too.

**Comment by prathikshetty2002** [comment]
Done
