### ISSUE TITLE
Update the EventList.js for the events page

### ISSUE THREAD

**Issue by prathikshetty2002** [DSC-TCET/gdsc-tcet-website#20]
- [x] Update the event list acc to the recent events

@Vansh-Baghel update this event list and co-ordinate with @sho-shoaib to get the event/gallery update #12 done.👍

@WilfredAlmeida review the work once they submit the PR

**Comment by Paras-code-007** [comment]
@prathikshetty2002  can you assign this issue to me!!

**Comment by Vansh-Baghel** [comment]
It will be completed as required !!

**Comment by prathikshetty2002** [comment]
> @prathikshetty2002 can you assign this issue to me!!

Actually this was assigned above in the issue comment to @Vansh-Baghel , we will create some new issues stay tuned for it.
